### ISSUE TITLE
Withdrawal following staking immediately incurs errors (LeedoNftVault.sol)

### ISSUE THREAD

**Issue by crazybae** [GoSquidGame/GoSquidGame.github.io#3]
If a token is staked and withdraw in a same block, the following errors occurs.
The withdraw function cannot read the associated token ID from the previous state.

Error message (ethers.js test)

Error: transaction failed (transactionHash="0x305114f7868cb86361f67463b9397a2f63500657359b88589689214d4474d219", transaction={"hash":"0x305114f7868cb86361f67463b9397a2f63500657359b88589689214d4474d219","type":2,"accessList":[],"blockHash":null,"blockNumber":null,"transactionIndex":null,"confirmations":0,"from":"0x4278827E51e1453af40ad3F454AE5b556823217c","gasPrice":{"type":"BigNumber","hex":"0x77359401"},"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x773593f9"},"maxFeePerGas":{"type":"BigNumber","hex":"0x77359401"},"gasLimit":{"type":"BigNumber","hex":"0x0771d5"},"to":"0xBF6CC26C2cA10B59AA68fca6EdAc0773cE306c97","value":{"type":"BigNumber","hex":"0x00"},"nonce":59,"data":"0x983d95ce000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000058000000000000000000000000000000000000000000000000000000000000002c00000000000000000000000000000000000000000000000000000000000000440000000000000000000000000000000000000000000000000000000000000037000000000000000000000000000000000000000000000000000000000000003a","r":"0x5876c8179d488f1a09e2ba87370aed900662416f1f7d785b3bcebc93ba5aa227","s":"0x71360df3452894fe6f7ef37e69998445a5400c26785080427041f63f64f25319","v":1,"creates":null,"chainId":5}, receipt={"to":"0xBF6CC26C2cA10B59AA68fca6EdAc0773cE306c97","from":"0x4278827E51e1453af40ad3F454AE5b556823217c","contractAddress":null,"transactionIndex":0,"gasUsed":{"type":"BigNumber","hex":"0x077130"},"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","blockHash":"0xdafc06d09f43e3c4e7603a7cf6fc8245aec84dffb430d3f41f855dc95af62eb8","transactionHash":"0x305114f7868cb86361f67463b9397a2f63500657359b88589689214d4474d219","logs":[],"blockNumber":5779784,"confirmations":1,"cumulativeGasUsed":{"type":"BigNumber","hex":"0x077130"},"effectiveGasPrice":{"type":"BigNumber","hex":"0x77359400"},"status":0,"type":2,"byzantium":true}, code=CALL_EXCEPTION, version=providers/5.5.0)
    at Logger.makeError (/home/kbae/src/GoSquidGame.github.io/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)
    at Logger.throwError (/home/kbae/src/GoSquidGame.github.io/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)
    at EthersProviderWrapper.<anonymous> (/home/kbae/src/GoSquidGame.github.io/node_modules/@ethersproject/providers/src.ts/base-provider.ts:1314:24)
    at step (/home/kbae/src/GoSquidGame.github.io/node_modules/@ethersproject/providers/lib/base-provider.js:48:23)
    at Object.next (/home/kbae/src/GoSquidGame.github.io/node_modules/@ethersproject/providers/lib/base-provider.js:29:53)
    at fulfilled (/home/kbae/src/GoSquidGame.github.io/node_modules/@ethersproject/providers/lib/base-provider.js:20:58) {
  reason: 'transaction failed',
  code: 'CALL_EXCEPTION',
  transactionHash: '0x305114f7868cb86361f67463b9397a2f63500657359b88589689214d4474d219',
  transaction: {
    hash: '0x305114f7868cb86361f67463b9397a2f63500657359b88589689214d4474d219',
    type: 2,
    accessList: [],
    blockHash: null,
    blockNumber: null,
    transactionIndex: null,
    confirmations: 0,
    from: '0x4278827E51e1453af40ad3F454AE5b556823217c',
    gasPrice: BigNumber { _hex: '0x77359401', _isBigNumber: true },
    maxPriorityFeePerGas: BigNumber { _hex: '0x773593f9', _isBigNumber: true },
    maxFeePerGas: BigNumber { _hex: '0x77359401', _isBigNumber: true },
    gasLimit: BigNumber { _hex: '0x0771d5', _isBigNumber: true },
    to: '0xBF6CC26C2cA10B59AA68fca6EdAc0773cE306c97',
    value: BigNumber { _hex: '0x00', _isBigNumber: true },
    nonce: 59,
    data: '0x983d95ce000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000058000000000000000000000000000000000000000000000000000000000000002c00000000000000000000000000000000000000000000000000000000000000440000000000000000000000000000000000000000000000000000000000000037000000000000000000000000000000000000000000000000000000000000003a',
    r: '0x5876c8179d488f1a09e2ba87370aed900662416f1f7d785b3bcebc93ba5aa227',
    s: '0x71360df3452894fe6f7ef37e69998445a5400c26785080427041f63f64f25319',
    v: 1,
    creates: null,
    chainId: 5,
    wait: [Function (anonymous)]
  },
  receipt: {
    to: '0xBF6CC26C2cA10B59AA68fca6EdAc0773cE306c97',
    from: '0x4278827E51e1453af40ad3F454AE5b556823217c',
    contractAddress: null,
    transactionIndex: 0,
    gasUsed: BigNumber { _hex: '0x077130', _isBigNumber: true },
    logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
    blockHash: '0xdafc06d09f43e3c4e7603a7cf6fc8245aec84dffb430d3f41f855dc95af62eb8',
    transactionHash: '0x305114f7868cb86361f67463b9397a2f63500657359b88589689214d4474d219',
    logs: [],
    blockNumber: 5779784,
    confirmations: 1,
    cumulativeGasUsed: BigNumber { _hex: '0x077130', _isBigNumber: true },
    effectiveGasPrice: BigNumber { _hex: '0x77359400', _isBigNumber: true },
    status: 0,
    type: 2,
    byzantium: true
  }
}

**Comment by GoSquidGame** [comment]
This is not a contract problem. After the stake tx is succeed, the following withdraw tx can read the correct state even on the same block height. It is just a wallet issue which try to get gas estimate before sending the tx. The previous tx is not processed yet, so the wallet can not estimate the correct gas. To enforce the tx, you just ignore the wallet warning or error, and send the tx to the same block.
